repository:
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
teams:
  - name: customer-products
    permission: admin
  - name: customer-products-collaborators
    permission: push
  - name: compliant-users
    permission: pull
branches:
  - name: master
    protection:
      required_status_checks: null
      required_pull_request_reviews: null
      enforce_admins: true
      restrictions:
        users: []
        teams: []
