version: 2

jobs:
  build:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - run: npx prettier --check "{.circleci,.github,manage-github-apps}/**/*"
      - run: find manage-github-apps/ -type f -name *.json | xargs -n 1 npx github:Financial-Times/manage-github-apps validate-config --config
