version: 2.1

orbs:
  node: circleci/node@4.6.0

jobs:
  build:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - node/install-npm:
          version: "7"
      - run: find manage-github-apps/ -type f -name "*.json" | xargs -n 1 npm exec -- github:Financial-Times/manage-github-apps validate-config --config
